name: Amazon Job Monitor

on:
  workflow_dispatch:

jobs:
  telegram-test:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram test
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAMBOTTOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAMCHATID }}
        run: |
          curl -s -X POST \
            "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            --data-urlencode text="🔔 Amazon Shift Alert bot is connected successfully!"
